### ISSUE TITLE
Typescript React syntax highlighting

### ISSUE THREAD

**Issue by fpigeonjr** [nickcernis/blackbird-theme#1]
Hi Nick, 
Love this minimalist theme for vscode.
In a Typescript React file, I lose syntax highliting as shown here. Is there any way to support this file type?

![SCR-20221004-em7](https://user-images.githubusercontent.com/4629398/193862050-44bf6a30-5c2a-46af-818e-41416273ef8c.png)

**Comment by nickcernis** [comment]
Thanks for the kind words and the report, Frank! I just released 0.1.3 with some improvements to TSX/JSX.

You should see the update prompt soon in the extensions pane, or when you next restart VS Code.

**Comment by fpigeonjr** [comment]
Thank you for the quick support.
🎉Yes all fixed now with the update!
