### ISSUE TITLE
Theme is removing Svelte extension syntax highlighting 

### ISSUE THREAD

**Issue by drewbitt** [nickcernis/blackbird-theme#2]
Blackbird is removing syntax highlighting in the HTML section of a .svelte file using the svelte official extension `svelte.svelte-vscode`. It is the only theme that I have that does this

![image](https://user-images.githubusercontent.com/26885897/210900875-1f87d37c-6e7a-4de6-b76f-e3411fbac79d.png)

What it looks like in other themes

![image](https://user-images.githubusercontent.com/26885897/210900956-3b808287-d633-4591-8625-04456dc6006e.png)

Editor tokens and scopes:
![image](https://user-images.githubusercontent.com/26885897/210901043-36b4fde0-b7f8-436c-8ac4-250b3324b75a.png)
![image](https://user-images.githubusercontent.com/26885897/210901140-8ff0b6d1-6cd0-47e0-ab59-2adbb1968c88.png)

**Comment by nickcernis** [comment]
Thanks for the report, @drewbitt, but I've decided not to maintain this theme. I'll shortly remove it and mark it as archived here.

I recommend [Night Owl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl) as the nearest alternative.
